services:
    metamodels.attribute_longtext.factory:
        class: MetaModels\AttributeLongtextBundle\Attribute\AttributeTypeFactory
        arguments:
            - '@database_connection'
            - '@metamodels.table_manipulator'
        tags:
          - { name: metamodels.attribute_factory }

    MetaModels\AttributeLongtextBundle\Schema\DoctrineSchemaGenerator:
      tags:
        - { name: 'metamodels.schema-generator.doctrine' }

#    MetaModels\AttributeLongtextBundle\FileUsage\FileUsageProvider:
#      public: true
#      arguments:
#        $factory: '@metamodels.factory'
#        $urlGenerator: '@router'
#        $requestStack: '@request_stack'
#        $csrfTokenManager: '@contao.csrf.token_manager'
#        $csrfTokenName: '%contao.csrf_token_name%'
#      tags:
#        - { name: contao_file_usage.provider }
